"""empty message

Revision ID: 3fe174b8a825
Revises: 
Create Date: 2024-08-23 19:45:10.836412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe174b8a825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=16),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###
